name = "Newman Pack"
author = "flench04"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18724b8314616bbcb04a4d2058176f4fc75248abd0833f7fae4883f1e626a9df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21.1"]
