name = "Newman Pack"
author = "flench04"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32d05b29d8295b0f6e432e9d9b421e0754c93399306f4a8129fc45da1957dd1c"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"

[options]
acceptable-game-versions = ["26.2"]
