name = "Newman Pack"
author = "flench04"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4575138d3bda5c0c236eb5e1403f305f39a1361ca82b9c046e15bb0794d4790e"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"

[options]
acceptable-game-versions = ["26.2"]
